package JJTP_DS_UA;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 * Created by JJTP on 11/11/2016.
 */
public class GUI
{
    private JPanel mainPanel;
    private JButton logOutButton;
    private JTable table1;

    public GUI()
    {
    }

    public String setNodeName()
    {
        String name = JOptionPane.showInputDialog("Welcome to System Y! Please enter your name.");

        while (name.equals(""))
        {
            System.out.println("Please enter a name.");
            JOptionPane.showMessageDialog(null, "Please enter a name.", "Authorization required", JOptionPane.INFORMATION_MESSAGE);
            name = JOptionPane.showInputDialog("Welcome to System Y! Please enter your name.");
        }

        //if (name == JOptionPane.CANCEL_OPTION)
        return name;
    }


    public void openPanel()
    {
        JFrame frame = new JFrame("System Y");
        $$$setupUI$$$(); // generated code bij IntelliJ GUI form (don't edit please!)
        frame.setContentPane(mainPanel);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setLocation(700, 300);
        frame.pack();
        frame.setVisible(true);
    }

    void logOutButtonActionListener(ActionListener al)
    {
        logOutButton.addActionListener(al);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        mainPanel.setAutoscrolls(false);
        mainPanel.setBackground(new Color(-15850431));
        mainPanel.setMinimumSize(new Dimension(450, 450));
        mainPanel.setPreferredSize(new Dimension(450, 450));
        table1 = new JTable();
        table1.setBackground(new Color(-16577215));
        table1.setGridColor(new Color(-14987010));
        table1.setName("");
        table1.setPreferredSize(new Dimension(400, 350));
        table1.setRowHeight(25);
        mainPanel.add(table1);
        logOutButton = new JButton();
        logOutButton.setFont(new Font(logOutButton.getFont().getName(), logOutButton.getFont().getStyle(), 18));
        logOutButton.setHorizontalAlignment(0);
        logOutButton.setMargin(new Insets(3, 18, 3, 18));
        logOutButton.setMinimumSize(new Dimension(150, 41));
        logOutButton.setPreferredSize(new Dimension(400, 45));
        logOutButton.setText("Log out");
        mainPanel.add(logOutButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return mainPanel;
    }
}
